# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_remove_ip_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='ip',
            name='password',
            field=models.CharField(default='00000', max_length=100),
        ),
    ]
