# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_remove_ip_ip_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='date',
        ),
        migrations.AddField(
            model_name='ip',
            name='user',
            field=models.CharField(default='0000', max_length=100),
        ),
    ]
