# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20170724_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='user',
        ),
    ]
