# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20170624_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='user',
        ),
    ]
