# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_ip_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='IP_serial',
        ),
    ]
