# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20170627_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='version',
            field=models.CharField(default='00000', max_length=200),
        ),
    ]
