# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_ip_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='IP_address',
            field=models.CharField(error_messages={'unique': 'Please enter a different IP address.'}, max_length=20),
        ),
    ]
