# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_ip_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
