# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_ip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
