# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_ip_ip_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='IP_serial',
            field=models.CharField(default='00000', max_length=200),
        ),
    ]
