# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20170627_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='IP_address',
            field=models.CharField(max_length=20),
        ),
    ]
