# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20170705_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autodiscover',
            name='host',
        ),
    ]
