# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_autodiscover_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleDeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='0000', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ip',
            name='IP_address_auto',
            field=models.CharField(default='0000', max_length=100),
        ),
    ]
