# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_delete_singledevicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleDeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_no', models.BooleanField(default=True, max_length=200)),
                ('version', models.CharField(default='00000', max_length=200)),
                ('IP_address_auto', models.CharField(default='0000', max_length=100)),
                ('model', models.CharField(default='00000', max_length=100)),
            ],
        ),
    ]
