# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_delete_singledevicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP_address', models.CharField(default='0000', max_length=200)),
            ],
        ),
    ]
