# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='IP_description',
            field=models.CharField(default='00000', max_length=200),
        ),
    ]
