# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_auto_20170724_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='password',
        ),
    ]
