# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_delete_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='username',
            field=models.CharField(default='00000', max_length=100),
        ),
    ]
